---
# Purpose: Default variables for role
# Last Updated: 2018.07.23
# Notes: Openshift required (pip install openshift) on invoking machine

- local_action:
    module: "shell cat {{ path_to_cert }}|base64 -w0"
  register: x509_crt

- local_action:
    module: "shell cat {{ path_to_raw_key }}|base64 -w0"
  register: x509_key

- debug: var=x509_crt
- debug: var=x509_key

- name: Create a Service object from an inline definition
  local_action:
    module: k8s
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ container_secret }}"
        namespace: default
      type: Opaque
      data:
        tls.crt: "{{ x509_crt.stdout }}"
        tls.key: "{{ x509_key.stdout }}"
    force: "{{ openssl_force_regeneration }}"
